CREATE DATABASE CadastroClientes
GO

USE CadastroClientes
GO

CREATE TABLE Clientes(
	Id UNIQUEIDENTIFIER PRIMARY KEY,
	Nome VARCHAR(100) NOT NULL,
	CPF VARCHAR(14) NOT NULL,
	Email VARCHAR(50) NOT NULL
)
GO

CREATE TABLE Enderecos(
	ID INT PRIMARY KEY,
	IdCliente UNIQUEIDENTIFIER NOT NULL,
	CEP VARCHAR(9) NOT NULL,
	Logradouro VARCHAR(200) NOT NULL,
	Numero INT NOT NULL,
	Bairro VARCHAR(200) NOT NULL,
	Cidade VARCHAR(200) NOT NULL,
	Estado VARCHAR(2) NOT NULL
)
GO

ALTER TABLE Enderecos add constraint FK_Enderecos_Clientes FOREIGN KEY(IdCliente) REFERENCES Clientes(Id);
GO